//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examadmin
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class carinfo
    {
        public int car_id { get; set; }
        public string mark { get; set; }
        public string cartitle { get; set; }
        public string model { get; set; }
        public string imgpath { get; set; }
        public int hwp { get; set; }
        public string cardescr { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
